[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[project]
name = "git-version-sync"
version = "1.8.1"
description = "Tools to sync and update semantic versions"
readme = "README.md"
authors = [
    { name = "Finsa-SC", email = "finsakusumaputra@gmail.com" }
]
requires-python = ">=3.11"
license = { text = "MIT" }
keywords = ["git", "versioning", "semver", "pyproject", "cli"]

dependencies = [
    "packaging>=26.3",
    "pytest>=9.1.1",
    "pytest-mock>=3.15.1",
]

[project.scripts]
git-version-sync = "git_version_sync.cli:main"

[project.urls]
Homepage = "https://github.com/Finsa-SC/git-version-sync"
Repository = "https://github.com/Finsa-SC/git-version-sync"
Issues = "https://github.com/Finsa-SC/git-version-sync/issues"
pypi = "https://pypi.org/project/git-version-sync/"
