class GitVersionSyncError(Exception):
    ...

class GitCommandError(GitVersionSyncError):
    ...

class GitPushError(GitCommandError):
    ...

class ConfigVersionMismatch(GitVersionSyncError):
    ...

class GitRemoteError(GitVersionSyncError):
    ...